// native/src/lib/PenaltyGate.tsx
import { useEffect, useState } from 'react';
import { AppState, Modal, View, Text, StyleSheet, Pressable } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { fonts } from './theme';
import { getMyPenalty, type ActivePenalty } from './api';

/**
 * Strafrunde: Wer ohne Abmeldung gefehlt hat, sieht bei jedem Kaltstart
 * diesen Hinweis — 20 Sekunden lang ohne Ausweg. Bewusst kein Snooze und
 * kein gespeicherter Zustand: Die Strafe soll nerven, bis das nächste
 * Training beginnt (Phase „warning"). Der Text ist auf jeder Stufe derselbe
 * und droht nur vage „weitere Konsequenzen" an — ob der falsche Spot kommt
 * (Stufe 2), verrät er nicht.
 */
const HOLD_SECONDS = 20;

function prettyDate(d: string): string {
	return new Date(`${d}T12:00:00`).toLocaleDateString('de-CH', {
		weekday: 'long',
		day: 'numeric',
		month: 'long'
	});
}

export function PenaltyGate() {
	const [penalty, setPenalty] = useState<ActivePenalty | null>(null);
	const [left, setLeft] = useState(HOLD_SECONDS);
	const [dismissed, setDismissed] = useState(false);

	useEffect(() => {
		let alive = true;
		const load = () => {
			void getMyPenalty()
				.then((res) => {
					if (alive && res.penalty && res.penalty.phase === 'warning') setPenalty(res.penalty);
				})
				.catch(() => undefined);
		};
		load();
		// Die Strafe kann entstehen, während die App im Hintergrund liegt —
		// dann kommt der Push, aber kein Kaltstart. Darum auch beim Zurückkehren
		// prüfen; einmal weggeklickt bleibt sie bis zum nächsten Kaltstart weg.
		const sub = AppState.addEventListener('change', (state) => {
			if (state === 'active') load();
		});
		return () => {
			alive = false;
			sub.remove();
		};
	}, []);

	useEffect(() => {
		if (!penalty || dismissed || left <= 0) return;
		const t = setTimeout(() => setLeft((n) => n - 1), 1000);
		return () => clearTimeout(t);
	}, [penalty, dismissed, left]);

	if (!penalty || dismissed) return null;
	const ready = left <= 0;

	return (
		<Modal visible transparent={false} animationType="fade" onRequestClose={() => undefined}>
			<View style={styles.screen}>
				<Ionicons name="warning" size={96} color="#ffd166" />
				<Text style={styles.title}>Nicht abgemeldet!</Text>
				<Text style={styles.body}>
					Am {prettyDate(penalty.missed.date)} warst du nicht im Training und hast dich nicht
					abgemeldet.
				</Text>
				<Text style={styles.body}>
					Bis {prettyDate(penalty.penalty.date)} siehst du bei „Wer zieht" nur Fragezeichen. Beim
					nächsten Mal drohen weitere Konsequenzen.
				</Text>
				<Text style={styles.hint}>Nächstes Mal: abmelden. Dauert zehn Sekunden.</Text>
				<Pressable
					disabled={!ready}
					onPress={() => setDismissed(true)}
					style={({ pressed }) => [styles.button, !ready && styles.buttonLocked, pressed && ready && { opacity: 0.8 }]}
				>
					<Text style={styles.buttonText}>{ready ? 'Verstanden' : `Verstanden (${left})`}</Text>
				</Pressable>
			</View>
		</Modal>
	);
}

const styles = StyleSheet.create({
	screen: {
		flex: 1,
		backgroundColor: '#5a0f14',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 28,
		gap: 16
	},
	title: {
		color: '#ffffff',
		fontFamily: fonts.sansBold,
		fontSize: 34,
		lineHeight: 40,
		textAlign: 'center',
		letterSpacing: 0.5
	},
	body: {
		color: '#ffffffe6',
		fontFamily: fonts.sans,
		fontSize: 17,
		lineHeight: 25,
		textAlign: 'center'
	},
	hint: {
		color: '#ffd166',
		fontFamily: fonts.sansSemi,
		fontSize: 14,
		lineHeight: 20,
		textAlign: 'center',
		marginTop: 4
	},
	button: {
		marginTop: 20,
		backgroundColor: '#ffd166',
		borderRadius: 14,
		paddingHorizontal: 28,
		paddingVertical: 14,
		minWidth: 200,
		alignItems: 'center'
	},
	buttonLocked: { backgroundColor: '#ffffff33' },
	buttonText: { color: '#1a0508', fontFamily: fonts.sansBold, fontSize: 16 }
});

// src/lib/components/PenaltyGate.svelte
<script lang="ts">
	/**
	 * Strafrunde: Warnhinweis für Leute, die ohne Abmeldung gefehlt haben.
	 *
	 * Erscheint bei jedem Öffnen (einmal pro Browser-Sitzung), bis das
	 * nächste Training beginnt — und lässt sich erst nach 20 Sekunden
	 * wegklicken. Bewusst unbequem: Wer sich nicht abmeldet, soll es einmal
	 * richtig merken. Der Text ist auf jeder Stufe derselbe und droht nur vage
	 * „weitere Konsequenzen" an — ob der falsche Spot kommt, verrät er nicht
	 * (siehe noShowPenalty.ts).
	 */
	import { onMount } from 'svelte';
	import { tapFeedback } from '$lib/haptics';

	type Penalty = {
		id: number;
		missed: { id: number; date: string; dayOfWeek: string };
		penalty: { id: number; date: string; dayOfWeek: string; timeStart: string; timeEnd: string };
		phase: 'warning' | 'wrongSpot';
	};

	const WAIT_SECONDS = 20;
	const SEEN_KEY = 'penalty-gate-seen';

	let penalty = $state<Penalty | null>(null);
	let secondsLeft = $state(WAIT_SECONDS);

	function prettyDate(d: string): string {
		return new Date(d + 'T12:00:00').toLocaleDateString('de-CH', {
			weekday: 'long',
			day: 'numeric',
			month: 'long'
		});
	}

	function seenThisSession(id: number): boolean {
		try {
			return sessionStorage.getItem(SEEN_KEY) === String(id);
		} catch {
			return false;
		}
	}

	function dismiss() {
		if (!penalty || secondsLeft > 0) return;
		tapFeedback();
		try {
			sessionStorage.setItem(SEEN_KEY, String(penalty.id));
		} catch {
			/* egal */
		}
		penalty = null;
	}

	let timer: ReturnType<typeof setInterval> | null = null;

	async function load() {
		if (penalty) return;
		try {
			const res = await fetch('/api/me/penalty', { credentials: 'include' });
			if (!res.ok) return;
			const data = (await res.json()) as { penalty: Penalty | null };
			if (!data.penalty || data.penalty.phase !== 'warning' || seenThisSession(data.penalty.id)) return;
			penalty = data.penalty;
			secondsLeft = WAIT_SECONDS;
			timer = setInterval(() => {
				secondsLeft = Math.max(0, secondsLeft - 1);
				if (secondsLeft === 0 && timer) clearInterval(timer);
			}, 1000);
		} catch {
			/* Hinweis ist Beiwerk */
		}
	}

	onMount(() => {
		void load();
		// Tab lag offen, Strafe kam später: beim Zurückkehren nachsehen.
		const onVisible = () => {
			if (document.visibilityState === 'visible') void load();
		};
		document.addEventListener('visibilitychange', onVisible);
		return () => {
			document.removeEventListener('visibilitychange', onVisible);
			if (timer) clearInterval(timer);
		};
	});
</script>

{#if penalty}
	<div
		class="fixed inset-0 z-[99] flex items-center justify-center bg-[#2a0608]/95 p-4 backdrop-blur-md"
		role="alertdialog"
		aria-modal="true"
		aria-labelledby="penalty-title"
	>
		<div class="w-full max-w-md rounded-2xl border-2 border-red-500/70 bg-[#3b0a0d] p-6 text-center shadow-2xl">
			<div class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-red-500/20 text-4xl" aria-hidden="true">
				⚠️
			</div>
			<p class="mt-4 font-display text-xs font-semibold uppercase tracking-[0.3em] text-red-300">
				Strafrunde
			</p>
			<h2 id="penalty-title" class="mt-1 font-display text-3xl font-bold uppercase tracking-wide text-red-100">
				Nicht abgemeldet!
			</h2>
			<p class="mt-4 text-base leading-relaxed text-red-50">
				Am <strong>{prettyDate(penalty.missed.date)}</strong> warst du nicht im Training und hast dich
				nicht abgemeldet.
			</p>
			<p class="mt-3 text-sm leading-relaxed text-red-200">
				Bis <strong>{prettyDate(penalty.penalty.date)}</strong> siehst du bei „Wer zieht" nur Fragezeichen.
				Beim nächsten Mal drohen <strong>weitere Konsequenzen</strong>.
			</p>
			<p class="mt-3 text-xs text-red-300/80">
				Nächstes Mal: einfach abmelden. Dauert fünf Sekunden.
			</p>
			<button
				type="button"
				onclick={dismiss}
				disabled={secondsLeft > 0}
				class="mt-6 w-full cursor-pointer rounded-lg bg-red-500 px-4 py-3 text-sm font-bold text-white transition-colors hover:bg-red-400 disabled:cursor-not-allowed disabled:bg-red-900 disabled:text-red-300"
			>
				{secondsLeft > 0 ? `Verstanden (${secondsLeft})` : 'Verstanden'}
			</button>
		</div>
	</div>
{/if}
